### ISSUE TITLE
Pdfork.OtherUserForked fails on FreeBSD 12 current

### ISSUE THREAD

**Issue by svmhdvn** [google/capsicum-test#19]
This test case tries to test killing a process created with `pdfork` as a different user. FreeBSD disallows this behaviour, so it fails with `EPERM`.

From `kill(2)`:
```
For a process to have permission to send a signal to a process designated
by pid, the user must be the super-user, or the real or saved user ID of
the receiving process must match the real or effective user ID of the
sending process.
```

Call stack:
```
sys_pdkill() -> p_cansignal() -> ... -> priv_check_cred()

int
priv_check_cred(struct ucred *cred, int priv, int flags)
{
        ...
        // No other policies grant privilege
        ...
        /*
	 * The default is deny, so if no policies have granted it, reject
	 * with a privilege error here.
	 */
	error = EPERM;
        ...
}
```

**Comment by emaste** [comment]
I believe this is a FreeBSD kernel bug: if we hold a pd for a process we should be able to kill that process, regardless of UID. But any change will need to be considered carefully.

**Comment by daviddrysdale** [comment]
From a pure capabilities PoV, it makes sense that the holder of a process descriptor (with `CAP_PDKILL` right) should be able to kill that process.

However, with Capsicum being a pragmatic blend of capabilities with POSIX, things are a bit less clear -- mostly Capsicum adds extra *restrictions* above those of POSIX, it doesn't normally allow you to do something new that you wouldn't otherwise be able to do.  (I'd worry in particular about future interactions if (say) we added the ability to create a process descriptor for an already-existing process.)

**Comment by emaste** [comment]
Fair enough; in that case, the test should be changed to codify the current FreeBSD behaviour.

**Comment by ngie-eign** [comment]
I'm not reproing this on 13.0-CURRENT.

@svmhdvn: could you please close this report?

**Comment by svmhdvn** [comment]
Sorry for the delay! Closing the issue now.
